In [1]:
#First, you import numpy and sklearn.linear_model.LinearRegression and provide known inputs and output

import numpy as np
from sklearn.linear_model import LinearRegression

x = [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]]
y = [4, 5, 20, 14, 32, 22, 38, 43]
x, y = np.array(x), np.array(y)

In [2]:
#In multiple linear regression, x is a two-dimensional array with at least two columns, while y is usually a one-dimensional array.
#This is a simple example of multiple linear regression, and x has exactly two columns.

print (x)
print(y)

[[ 0  1]
 [ 5  1]
 [15  2]
 [25  5]
 [35 11]
 [45 15]
 [55 34]
 [60 35]]
[ 4  5 20 14 32 22 38 43]


In [3]:
model = LinearRegression().fit(x, y)

In [4]:
#You obtain the value of 𝑅² using .score() and the values of the estimators of regression 
#coefficients with .intercept_ and .coef_. Again, .intercept_ holds the bias 𝑏₀, while now .coef_ is an 
#array containing 𝑏₁ and 𝑏₂ respectively.

#In this example, the intercept is approximately 5.52, 
#and this is the value of the predicted response when 𝑥₁ = 𝑥₂ = 0. 
#The increase of 𝑥₁ by 1 yields the rise of the predicted response by 0.45. 
#Similarly, when 𝑥₂ grows by 1, the response rises by 0.26.



r_sq = model.score(x, y)
print('coefficient of determination:', r_sq)
print('intercept:', model.intercept_)
print('slope:', model.coef_)


coefficient of determination: 0.8615939258756776
intercept: 5.52257927519819
slope: [0.44706965 0.25502548]


In [5]:
y_pred = model.predict(x)
print('predicted response:', y_pred, sep='\n')

predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [6]:
#You can predict the output values by multiplying each column of the input with the appropriate weight, 
#summing the results and adding the intercept to the sum.


y_pred = model.intercept_ + np.sum(model.coef_ * x, axis=1)
print('predicted response:', y_pred, sep='\n')

predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [9]:


#You can apply this model to new data as well:x_new = np.arange(10).reshape((-1, 2))
x_new = np.arange(10).reshape((-1, 2))
print(x_new)

y_new = model.predict(x_new)
print(y_new)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[ 5.77760476  7.18179502  8.58598528  9.99017554 11.3943658 ]
