In [1]:
#There is only one extra step: you need to transform the array of inputs to include non-linear terms such as 𝑥².

import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures


In [3]:
#Now you have the input and output in a suitable format. 
#Keep in mind that you need the input to be a two-dimensional array. That’s why .reshape() is used.


x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([15, 11, 2, 8, 25, 32])

In [6]:
#This is the new step you need to implement for polynomial regression!

#As you’ve seen earlier, you need to include 𝑥² (and perhaps other terms) as additional features when implementing polynomial regression. For that reason, you should transform the input array x to contain the additional column(s) with the values of 𝑥² (and eventually more features).

#It’s possible to transform the input array in several ways (like using insert() from numpy), but the class PolynomialFeatures is very convenient for this purpose. Let’s create an instance of this class:

transformer = PolynomialFeatures(degree=2, include_bias=False)

#The variable transformer refers to an instance of PolynomialFeatures which you can use to transform the input x.

#You can provide several optional parameters to PolynomialFeatures:

#degree is an integer (2 by default) that represents the degree of the polynomial regression function.
#interaction_only is a Boolean (False by default) that decides whether to include only interaction features (True) or all features (False).
#include_bias is a Boolean (True by default) that decides whether to include the bias (intercept) column of ones (True) or not (False).




In [7]:
#This example uses the default values of all parameters, but you’ll sometimes want to experiment with the degree of the function, and it can be beneficial to provide this argument anyway.

#Before applying transformer, you need to fit it with .fit():

transformer.fit(x)
    
    
    

PolynomialFeatures(include_bias=False)

In [8]:
#Once transformer is fitted, it’s ready to create a new, modified input. You apply .transform() to do that:
x_ = transformer.transform(x)

#That’s the transformation of the input array with .transform(). It takes the input array as the argument and returns the modified array.

In [9]:
#You can also use .fit_transform() to replace the three previous statements with only one:
x_ = PolynomialFeatures(degree=2, include_bias=False).fit_transform(x)

In [10]:
#That’s fitting and transforming the input array in one statement with .fit_transform(). 
#It also takes the input array and effectively does the same thing as .fit() and .transform() called in that order. 
#It also returns the modified array. This is how the new input array looks:

print(x_)

[[   5.   25.]
 [  15.  225.]
 [  25.  625.]
 [  35. 1225.]
 [  45. 2025.]
 [  55. 3025.]]


In [11]:
model = LinearRegression().fit(x_, y)

In [12]:
#Again, .score() returns 𝑅². Its first argument is also the modified input x_, not x. 
#The values of the weights are associated to .intercept_ and .coef_: .intercept_ represents 𝑏₀, while .coef_ references the array that contains 𝑏₁ and 𝑏₂ respectively.



r_sq = model.score(x_, y)
print('coefficient of determination:', r_sq)
print('intercept:', model.intercept_)
print('coefficients:', model.coef_)

coefficient of determination: 0.8908516262498563
intercept: 21.372321428571418
coefficients: [-1.32357143  0.02839286]


In [13]:
#You can obtain a very similar result with different transformation and regression arguments:

x_ = PolynomialFeatures(degree=2, include_bias=True).fit_transform(x)

In [14]:
#This is how the modified input array looks in this case:

print(x_)

#The first column of x_ contains ones, the second has the values of x, while the third holds the squares of x.

[[1.000e+00 5.000e+00 2.500e+01]
 [1.000e+00 1.500e+01 2.250e+02]
 [1.000e+00 2.500e+01 6.250e+02]
 [1.000e+00 3.500e+01 1.225e+03]
 [1.000e+00 4.500e+01 2.025e+03]
 [1.000e+00 5.500e+01 3.025e+03]]


In [15]:
#The intercept is already included with the leftmost column of ones, and you don’t need to include it again 
#when creating the instance of LinearRegression. Thus, you can provide fit_intercept=False. 
#This is how the next statement looks:

model = LinearRegression(fit_intercept=False).fit(x_, y)
    
    
    

In [16]:
r_sq = model.score(x_, y)
print('coefficient of determination:', r_sq)
print('intercept:', model.intercept_)
print('coefficients:', model.coef_)

#ou see that now .intercept_ is zero, but .coef_ actually contains 𝑏₀ as its first element. Everything else is the same.

coefficient of determination: 0.8908516262498565
intercept: 0.0
coefficients: [21.37232143 -1.32357143  0.02839286]


In [17]:
#If you want to get the predicted response, just use .predict(), but remember that the argument should be the modified input x_ instead of the old x:

y_pred = model.predict(x_)
print('predicted response:', y_pred, sep='\n')

predicted response:
[15.46428571  7.90714286  6.02857143  9.82857143 19.30714286 34.46428571]


In [18]:
#You can apply the identical procedure if you have several input variables. You’ll have an input array with more than one column, but everything else is the same. Here is an example:

# Step 1: Import packages
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

# Step 2a: Provide data
x = [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]]
y = [4, 5, 20, 14, 32, 22, 38, 43]
x, y = np.array(x), np.array(y)

# Step 2b: Transform input data
x_ = PolynomialFeatures(degree=2, include_bias=False).fit_transform(x)

# Step 3: Create a model and fit it
model = LinearRegression().fit(x_, y)

# Step 4: Get results
r_sq = model.score(x_, y)
intercept, coefficients = model.intercept_, model.coef_

# Step 5: Predict
y_pred = model.predict(x_)

In [19]:
print('coefficient of determination:', r_sq)

print('intercept:', intercept)

print('coefficients:', coefficients, sep='\n')

print('predicted response:', y_pred, sep='\n')


#In this case, there are six regression coefficients (including the intercept), as shown in the estimated regression function 𝑓(𝑥₁, 𝑥₂) = 𝑏₀ + 𝑏₁𝑥₁ + 𝑏₂𝑥₂ + 𝑏₃𝑥₁² + 𝑏₄𝑥₁𝑥₂ + 𝑏₅𝑥₂².

#You can also notice that polynomial regression yielded a higher coefficient of determination than multiple linear regression for the same problem. At first, you could think that obtaining such a large 𝑅² is an excellent result. It might be.

#However, in real-world situations, having a complex model and 𝑅² very close to 1 might also be a sign of overfitting. To check the performance of a model, you should test it with new data, that is with observations not used to fit (train) the model.


coefficient of determination: 0.9453701449127819
intercept: 0.8430556452395876
coefficients:
[ 2.44828275  0.16160353 -0.15259677  0.47928683 -0.4641851 ]
predicted response:
[ 0.54047408 11.36340283 16.07809622 15.79139    29.73858619 23.50834636
 39.05631386 41.92339046]
